server:
  port: 8083
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  profiles:
    include: secret
  application:
    name: api_gateway_service
#  rabbitmq:
#    host: 127.0.0.1
#    port: 5672
#    username: guest
#    password: guest
    cloud:
      gateway:
        routes:
          - id: msa_user
            uri: lb://USER-SERVICE
            predicates:
              - Path=/api/v1/user/**
              - Method=GET, POST, PATCH, DELETE
            filters:
              - RemoveRequestHeader=Cookie
              - AuthorizationFilter

          - id: msa_user_login
            uri: lb://USER-SERVICE
            predicates:
              - Path=/api/v1/user/**
              - Method=POST
            filters:
              - RemoveRequestHeader=Cookie

          - id: msa_order
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/api/v1/order
              - Method=GET, POST, PUT
            filters:
              - RemoveRequestHeader=Cookie
              - RewritePath=/productService/(?<segment>.*), /${segment}
              - AuthorizationHeaderFilter

          - id: msa_product
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/api/v1/product
              - Method=GET, POST, PUT, DELETE
            filters:
              - RemoveRequestHeader=Cookie
  data:
    redis:
      host: 127.0.0.1
      port: 6379

management:
  endpoints:
    web:
      exposure:
#Refresh : 컨텍스트 다시 로드, health : 애플리케이션의 상태 확인, beans : 애플리케이션의 빈 정보 확인
#        httptrace : 최근 요청, 응답 추정, busrefresh : 클러스터 내에서 설정을 다시 로드
        include: refresh, health, beans, httptrace, busrefresh



