#spring.application.name=api_gateway
spring:
  application:
    name: api_gateway
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8080
          predicates:
            - Path=/api/v1/user/**
            - Path=/api/v1/user-order/**
            - Path=/api/v1/my-page/**
#            - Path=/api/v1/my-product/**
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/product/**
            - Path=/api/v1/product-detail/**
            - Path=/api/v1/cart/**
            - Path=/api/v1/order-to-product/**
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/order/**
            - Path=/api/v1/order-detail/**
            - Path=/api/v1/delivery/**
server:
  port: 8083
