server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: api_gateway
  config:
    import: "optional:configserver:"
#  cloud:
#    gateway:
#      routes:
#        - id: user-service
#          uri: lb://user-service
#          predicates:
#            - Path=/api/v1/user/**
#            - Path=/api/v1/user-order/**
#            - Path=/api/v1/my-page/**
#        - id: product-service
#          uri: lb://product-service
#          predicates:
#            - Path=/api/v1/product/**
#            - Path=/api/v1/product-detail/**
#            - Path=/api/v1/cart/**
#            - Path=/api/v1/order-to-product/**
#        - id: order-service
#          uri: lb://order-service
#          predicates:
#            - Path=/api/v1/order/**
#            - Path=/api/v1/order-detail/**
#            - Path=/api/v1/delivery/**
