#server:
#  port: 8083

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

spring:
  application:
    name: msa_gateway
  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://msa_user
          predicates:
            - Path=/api/v1/user/**
        - id: product
          uri: lb://msa_product
          predicates:
            - Path=/api/v1/product/**
        - id: order
          uri: lb://msa_order
          predicates:
            - Path=/api/v1/product/**